### PR TITLE
Improve short sha

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by janisozaur** [comment]
Sorry, I've got no clue why `Build / build` and `Build / compile` fail anymore - I've fixed all the linting and formatting errors in submitted code already.

**Review by proudust — CHANGES_REQUESTED** [review]
Thanks for the pull request, and sorry for the late reply!
Before merging, could you run `deno task build` to update `dist/actions.js` and `dist/cli.js`, and then commit those changes, which should make the `Build / build` action pass.

**Comment by janisozaur** [comment]
The `Build / build` is fixed now, but `Build / compile` still fails due to error when writing temp file.

**Comment by proudust** [comment]
I’m not sure why the `Build / compile` is failing, but it works locally, so I think it’s probably fine. I’ll go ahead and merge. Thanks!

**Pull request merged**
